Controllers/BookController.cs
using LibraryManagementSystem.Data;
using LibraryManagementSystem.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace LibraryManagementSystem.Controllers
{
    public class BookController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BookController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var book = (from b in _context.Book
                        join c in _context.Category on b.CategoryId equals c.CategoryId
                        select new BookViewModel
                        {
                            BookId = b.BookId,
                            Title = b.Title,
                            Author = b.Author,
                            ISBN = b.ISBN,
                            PublisherName = b.PublisherName,
                            PublishedDate = b.PublishedDate,
                            TotalCopies = b.TotalCopies,
                            AvailableCopies = b.AvailableCopies,
                            CoverImageURL = b.CoverImageURL,
                            BorrowRecords = _context.BorrowRecord.Where(br => br.BookId == b.BookId).ToList(),
                            CategoryId = b.CategoryId,
                            CategoryName = c.CategoryName
                        }).ToList();

            return View(book);
        }


        // GET: Create Book page
        public IActionResult CreateBook()
        {
            var categories = _context.Category
                .Select(c => new SelectListItem
                {
                    Value = c.CategoryId.ToString(),
                    Text = c.CategoryId.ToString()  
                })
                .ToList();

            ViewBag.Category = categories;

            return View();
        }


        // POST: Create Book
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateBook(Book book)
        {
            _context.Book.Add(book);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        // GET: Edit Book
        public IActionResult EditBook(int id)
        {
            var book = _context.Book.FirstOrDefault(b => b.BookId == id);

            if (book == null)
                return NotFound();
            var categories = _context.Category
                .Select(c => new SelectListItem
                {
                    Value = c.CategoryId.ToString(),
                    Text = c.CategoryId.ToString()
                })
                .ToList();

            ViewBag.Category = categories;

            return View(book);
        }

        // POST: Edit Book
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditBook(int id, Book updatedBook)
        {
            if (ModelState.IsValid)
            {
                _context.Update(updatedBook);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View("EditBook", updatedBook);
        }

        // POST: Delete via SweetAlert + AJAX
        [HttpPost]
        public IActionResult DeleteBook(int id)
        {
            var book = _context.Book.FirstOrDefault(b => b.BookId == id);

            if (book == null)
                return NotFound();

            _context.Book.Remove(book);
            _context.SaveChanges();
            return Ok();
        }
    }
}

Controllers/BookRequestController.cs
using Microsoft.AspNetCore.Mvc;

namespace LibraryManagementSystem.Controllers
{
    public class BookRequestController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/CategoryController.cs
using LibraryManagementSystem.Data;
using LibraryManagementSystem.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace LibraryManagementSystem.Controllers
{
    [Authorize(Roles ="Admin")]
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CategoryController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Book list
        public IActionResult Index()
        {
            var category = _context.Category.ToList();
            return View(category);
        }

        public IActionResult CreateCategory()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateCategory(Category category)
        {


            _context.Category.Add(category);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");

        }
        public IActionResult EditCategory(int id)
        {
            var category = _context.Category.FirstOrDefault(b => b.CategoryId == id);

            if (category == null)
                return NotFound();

            return View(category);
        }

        // POST: Edit Book
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditCategory(int id, Category updateCategory)
        {
            if (ModelState.IsValid)
            {
                _context.Update(updateCategory);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View("EdiCategory", updateCategory);
        }

        // POST: Delete via SweetAlert + AJAX
        [HttpPost]
        public IActionResult DeleteCategory(int id)
        {
            var category = _context.Category.FirstOrDefault(b => b.CategoryId == id);

            if (category == null)
                return NotFound();

            _context.Category.Remove(category);
            _context.SaveChanges();
            return Ok(); // For AJAX success
        }
    }
}

Controllers/UserController.cs
//UserController.cs
using LibraryManagementSystem.Data;
using Microsoft.AspNetCore.Mvc;
using LibraryManagementSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Identity;
using LibraryManagementSystem.ViewModels;
using System.Threading.Tasks;

namespace LibraryManagementSystem.Controllers
{
    public class UserController : Controller
    {
        private readonly UserManager<IdentityUser> _user;
        private readonly RoleManager<IdentityRole> _role;
        public UserController(UserManager<IdentityUser>user, RoleManager<IdentityRole> role)
        {
            _role = role;
            _user = user;
        }
        public IActionResult Index()
        {
           return View();
        }
        public async Task<IActionResult> UserDetail()
        {
            var GetUser = _user.Users.ToList(); 
            var userRole = new List<UserRoleViewModel>();
            foreach (var user in GetUser)
            {
                var roles = await _user.GetRolesAsync(user);
                userRole.Add(new UserRoleViewModel
                {
                    UserId = user.Id,
                    Email = user.Email,
                    Roles = roles.ToList()
                });
            }
            return View(userRole);
        }
    }
}

Views/Shared/Admin_Layout.cshtml
@*  @using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Identity 
@{
    // var isAdmin = Context.Session.GetString("IsAdmin") == "true";
    // var adminEmail = Context.Session.GetString("AdminEmail");
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>Admin Dashboard</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700&display=swap" rel="stylesheet">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Admin/plugins/fontawesome-free/css/all.min.css" />
    <!-- AdminLTE -->
    <link rel="stylesheet" href="~/Admin/dist/css/adminlte.min.css" />
</head>
<body class="hold-transition layout-top-nav">
    <div class="wrapper">
        <nav class="main-header navbar navbar-expand-md navbar-light bg-white border-bottom shadow-sm">
            <div class="container">
                <a href="/" class="navbar-brand">
                    <i class="fas fa-book-reader mr-1"></i>
                    <span class="brand-text font-weight-bold">Library Management System</span>
                </a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav ml-auto align-items-center">
                       if (isAdmin)
                        { 
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Category" asp-action="Index">
                                    <i class="fas fa-plus-circle"></i>Categories
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Book" asp-action="Index">
                                    <i class="fas fa-book"></i>Books
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="BorrowRecord" asp-action="Index">
                                    <i class="fas fa-book"></i>Borrow Record
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="BookRequest" asp-action="Index">
                                    <i class="fas fa-book"></i>Book Request
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-page="/Admin/UserList/Index">
                                    <i class="fas fa-users"></i> User List
                                </a>
                            </li> 
                            <li class="nav-item">
                                <span class="nav-link text-primary">
                                    <i class="fas fa-user-circle"></i> Hello, @adminEmail
                                </span>
                            </li>
                            <li class="nav-item">
                                <form class="form-inline" method="post" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="/">
                                    <button type="submit" class="btn btn-outline-dark btn-sm ml-2">
                                        <i class="fas fa-sign-out-alt"></i> Logout
                                    </button>
                                </form>
                            </li>
                        
                    </ul>
                </div>
            </div>
        </nav>

        <!-- Content Wrapper -->
        <div class="content-wrapper">
            <div class="content">
                <div class="container py-4">
                    @RenderBody()
                </div>
            </div>
        </div>

        <!-- Footer -->
        <footer class="main-footer text-center small bg-white shadow-sm">
            <strong>&copy; 2025 - All Rights Reserved</strong>
        </footer>
    </div>

    <!-- Scripts -->
    <script src="~/Admin/plugins/jquery/jquery.min.js"></script>
    <script src="~/Admin/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/Admin/dist/js/adminlte.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>  *@

Views/Shared/UserLayout.cshtml
@using Microsoft.AspNetCore.Identity  
@inject SignInManager<IdentityUser> SignInManager  
@inject UserManager<IdentityUser> UserManager  

<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="utf-8" />  
    <title>Library Management System</title>  

    <!-- Google Font -->  
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700&display=swap" rel="stylesheet">  
    <!-- Font Awesome -->  
    <link rel="stylesheet" href="~/Admin/plugins/fontawesome-free/css/all.min.css" />  
    <!-- AdminLTE -->  
    <link rel="stylesheet" href="~/Admin/dist/css/adminlte.min.css" />  
</head>  
<body class="hold-transition layout-top-nav">  
    <div class="wrapper">  

        <!-- Navbar -->  
        <nav class="main-header navbar navbar-expand-md navbar-light bg-white border-bottom shadow-sm">  
            <div class="container">  

                <a href="~/" class="navbar-brand">  
                    <i class="fas fa-book-reader mr-1"></i>  
                    <span class="brand-text font-weight-bold">Library Management System</span>  
                </a>  

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse">  
                    <span class="navbar-toggler-icon"></span>  
                </button>  

                <div class="collapse navbar-collapse" id="navbarCollapse">  
                    <ul class="navbar-nav ml-auto align-items-center">  
                       
                        @if (SignInManager.IsSignedIn(User))  
                        {  
                            @if (User.IsInRole("Admin"))  
                            {  
                                <li class="nav-item">  
                                    <a class="nav-link" asp-controller="Category" asp-action="Index">  
                                        <i class="fas fa-plus-circle"></i>Categories  
                                    </a>  
                                </li>  
                                <li class="nav-item">  
                                    <a class="nav-link" asp-controller="Book" asp-action="Index">  
                                        <i class="fas fa-book"></i>Books  
                                    </a>  
                                </li>  
                                <li class="nav-item">  
                                    <a class="nav-link" asp-controller="BorrowRecord" asp-action="Index">  
                                        <i class="fas fa-book"></i>Borrow Record  
                                    </a>  
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="User" asp-action="UserDetail">
                                        <i class="fas fa-book"></i>User Details
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="Identity" asp-page="/Account/Manage/Index">
                                        <i class="fas fa-user-circle"></i> Hello, @UserManager.GetUserName(User)!
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <form class="form-inline" method="post" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="/">
                                        <button type="submit" class="btn btn-outline-dark btn-sm ml-2">
                                            <i class="fas fa-sign-out-alt"></i> Logout
                                        </button>
                                    </form>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Book" asp-action="Index">
                                        <i class="fas fa-book"></i>Books
                                    </a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link" asp-area="Identity" asp-page="/Account/Manage/Index">
                                        <i class="fas fa-user-circle"></i> Hello, @UserManager.GetUserName(User)!
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <form class="form-inline" method="post" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="/">
                                        <button type="submit" class="btn btn-outline-dark btn-sm ml-2">
                                            <i class="fas fa-sign-out-alt"></i> Logout
                                        </button>
                                    </form>
                                </li>
                            }
                           
                        }  
                        else  
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Book" asp-action="Index">
                                    <i class="fas fa-book"></i>Books
                                </a>
                            </li>
                            <li class="nav-item">  
                                <a class="nav-link" asp-area="Identity" asp-page="/Account/Login">  
                                    <i class="fas fa-sign-in-alt"></i> Login  
                                </a>  
                            </li>  
                            <li class="nav-item">  
                                <a class="nav-link" asp-area="Identity" asp-page="/Account/Register">  
                                    <i class="fas fa-user-plus"></i> Register  
                                </a>  
                            </li>  
                        }  
                    </ul>  
                </div>  
            </div>  
        </nav>  
        <!-- /.navbar -->  
        <!-- Content Wrapper -->  
        <div class="content-wrapper">  
            <div class="content">  
                <div class="container py-4">  
                    @RenderBody()  
                </div>  
            </div>  
        </div>  

        <footer class="main-footer text-center small bg-white shadow-sm">  
            <strong>  
                &copy; 2025 - All Rights Reserved  
            </strong>  
        </footer>  

    </div>  

    <!-- Scripts -->  
    <script src="~/Admin/plugins/jquery/jquery.min.js"></script>  
    <script src="~/Admin/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>  
    <script src="~/Admin/dist/js/adminlte.min.js"></script>  

    @RenderSection("Scripts", required: false)  
</body>  
</html>

Views/Shared/_Layout.cshtml
 <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    @* <title>@ViewData["Title"] - LibraryManagementSystem</title> *@
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LibraryManagementSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LibraryManagementSystem</a>
               
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarCollapse">

                    <!-- Right Side: Login/Register -->
                    <ul class="navbar-nav ms-auto">
                        @using Microsoft.AspNetCore.Identity
                        @using Microsoft.AspNetCore.Http
                        @inject SignInManager<IdentityUser> SignInManager
                        @inject UserManager<IdentityUser> UserManager

                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Manage/Index">
                                    Hello, @UserManager.GetUserName(User)!
                                </a>
                            </li>
                            <li class="nav-item">
                                <form class="form-inline" method="post" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="/">
                                    <button type="submit" class="btn nav-link btn-link text-dark">Logout</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Register</a>
                            </li>
                        }
                    </ul>

                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @* <footer class="border-top footer text-muted">
        <div class="container">
            @*  &copy; 2025 - LibraryManagementSystem 
        </div>
    </footer> *@

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html> 